DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS language CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS quiz CASCADE;
DROP TABLE IF EXISTS quiz_questions CASCADE;
DROP TABLE IF EXISTS score CASCADE;

-- 01 USER TABLE
CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  avatar VARCHAR,
  created_at TIMESTAMP, 
  role VARCHAR(255) NOT NULL DEFAULT 'Student'
);

--02 LANGUAGE TABLE
CREATE TABLE language (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL
);

--03 QUESTION TABLE
CREATE TABLE questions (
  id SERIAL PRIMARY KEY NOT NULL,
  question TEXT NOT NULL,
  answer_a TEXT NOT NULL,
  answer_b TEXT NOT NULL,
  answer_c TEXT NOT NULL,
  answer_d TEXT NOT NULL,
  correct TEXT NOT NULL,
  created_at TIMESTAMP, 
  language_id INTEGER REFERENCES language(id) ON DELETE CASCADE
);

--04 QUIZ TABLE
CREATE TABLE quiz (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL
);

--05 QUIZ_QUESTIONS TABLE
CREATE TABLE quiz_questions (
  id SERIAL PRIMARY KEY NOT NULL,
  questions_id INTEGER REFERENCES questions(id) ON DELETE CASCADE,
  quiz_id INTEGER REFERENCES quiz(id) ON DELETE CASCADE
);

--06 SCORE TABLE
CREATE TABLE score (
  id SERIAL PRIMARY KEY NOT NULL,
  quiz_questions_id INTEGER REFERENCES quiz_questions(id) ON DELETE CASCADE,
  users_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);